### ISSUE TITLE
Genome binning

### ISSUE THREAD

**Issue by SilasK** [pnnl/atlas#57]
@brwnj  I' started implementing concoct and am hesitating to use anvi'o. which has a lot of additional tools (may be too much).. what do you think?

**Comment by brwnj** [comment]
If you decide you _really_ want to dive into it, I would make it an optional protocol and a separate conda environment -- like you're starting to do with concoct. That way we have a primary conda env for the default and optional environments for alternate processing paths.

It's been a while since I used anvio. It can't be as bad as CheckM's install, right?

**Comment by SilasK** [comment]
Hehe, Anvi'o can be inst via bioconda now.
